/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.edusys.ui;

import com.edusys.dao.NhanVienDAO;
import com.edusys.entity.NhanVien;
import com.edusys.untis.Auth;
import com.edusys.untis.MsgBox;
import com.edusys.untis.XImage;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author tankh
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Color panedefault;
    Color paneclick;

    public Home() {

        initComponents();

        this.getContentPane().setBackground(new Color(255, 255, 255));
        panedefault = new Color(255, 255, 255);
        paneclick = new Color(124, 25, 83);

        form1.setBackground(new Color(227, 80, 168));
        form2.setBackground(new Color(143, 137, 183));
        form3.setBackground(new Color(143, 137, 183));
        form4.setBackground(new Color(143, 137, 183));
        form5.setBackground(new Color(143, 137, 183));
        form6.setBackground(new Color(143, 137, 183));

        pane1.setBackground(paneclick);
        pane2.setBackground(panedefault);
        pane3.setBackground(panedefault);
        pane4.setBackground(panedefault);
        pane5.setBackground(panedefault);
        pane6.setBackground(panedefault);

        form7.setBackground(new Color(143, 137, 183));
        pane7.setBackground(panedefault);
        TrangChu tc = new TrangChu();
        jDesktopPane1.add(tc).setVisible(true);
        init();
        
        this.customizeButton(btnDangXuat);
        this.customizeButton(btnDoiMatKhau);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        trangThai = new javax.swing.JPanel();
        lblDongHo = new javax.swing.JLabel();
        txtUS = new javax.swing.JLabel();
        txtRole = new javax.swing.JLabel();
        lblNgayThang = new javax.swing.JLabel();
        menu = new keeptoo.KGradientPanel();
        form1 = new javax.swing.JPanel();
        pane1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        form2 = new javax.swing.JPanel();
        pane2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        form3 = new javax.swing.JPanel();
        pane3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        form4 = new javax.swing.JPanel();
        pane4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        form5 = new javax.swing.JPanel();
        pane5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        form6 = new javax.swing.JPanel();
        pane6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        btnDoiMatKhau = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        form7 = new javax.swing.JPanel();
        pane7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        lblKiriko = new javax.swing.JLabel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(33, 36, 77));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/exit2.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Github-Octicons-Horizontal-rule-16.24.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(800, 800, 800)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(jLabel9)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 700, 460));

        trangThai.setBackground(new java.awt.Color(227, 80, 168));

        lblDongHo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblDongHo.setText("sss");

        txtUS.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtUS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Graphicloads-Flat-Finance-Person.24.png"))); // NOI18N
        txtUS.setText("ssss");

        txtRole.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtRole.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Graphicloads-100-Flat-Bucket.24.png"))); // NOI18N
        txtRole.setText("ssss");

        lblNgayThang.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblNgayThang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Ampeross-Qetto-2-Timer.24.png"))); // NOI18N
        lblNgayThang.setText("s");

        javax.swing.GroupLayout trangThaiLayout = new javax.swing.GroupLayout(trangThai);
        trangThai.setLayout(trangThaiLayout);
        trangThaiLayout.setHorizontalGroup(
            trangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangThaiLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblNgayThang, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUS, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRole, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );
        trangThaiLayout.setVerticalGroup(
            trangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trangThaiLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(trangThaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUS)
                    .addComponent(txtRole)
                    .addComponent(lblDongHo)
                    .addComponent(lblNgayThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(trangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 510, 40));

        menu.setkEndColor(new java.awt.Color(143, 137, 183));
        menu.setkStartColor(new java.awt.Color(143, 137, 183));

        form1.setBackground(new java.awt.Color(143, 137, 183));
        form1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        form1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                form1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pane1Layout = new javax.swing.GroupLayout(pane1);
        pane1.setLayout(pane1Layout);
        pane1Layout.setHorizontalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane1Layout.setVerticalGroup(
            pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Home111.png"))); // NOI18N
        jLabel2.setText("Trang chủ");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout form1Layout = new javax.swing.GroupLayout(form1);
        form1.setLayout(form1Layout);
        form1Layout.setHorizontalGroup(
            form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form1Layout.createSequentialGroup()
                .addComponent(pane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        form1Layout.setVerticalGroup(
            form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form1Layout.createSequentialGroup()
                .addGroup(form1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        form2.setBackground(new java.awt.Color(143, 137, 183));
        form2.setForeground(new java.awt.Color(255, 255, 255));
        form2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        form2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                form2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pane2Layout = new javax.swing.GroupLayout(pane2);
        pane2.setLayout(pane2Layout);
        pane2Layout.setHorizontalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane2Layout.setVerticalGroup(
            pane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Graphicloads-Flat-Finance-Person.24.png"))); // NOI18N
        jLabel4.setText("Nhân viên ");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout form2Layout = new javax.swing.GroupLayout(form2);
        form2.setLayout(form2Layout);
        form2Layout.setHorizontalGroup(
            form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form2Layout.createSequentialGroup()
                .addComponent(pane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        form2Layout.setVerticalGroup(
            form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form2Layout.createSequentialGroup()
                .addGroup(form2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        form3.setBackground(new java.awt.Color(143, 137, 183));
        form3.setForeground(new java.awt.Color(255, 255, 255));
        form3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        form3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                form3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pane3Layout = new javax.swing.GroupLayout(pane3);
        pane3.setLayout(pane3Layout);
        pane3Layout.setHorizontalGroup(
            pane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane3Layout.setVerticalGroup(
            pane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Blackvariant-Button-Ui-System-Folders-Drives-Users.24.png"))); // NOI18N
        jLabel5.setText("Khách hàng");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout form3Layout = new javax.swing.GroupLayout(form3);
        form3.setLayout(form3Layout);
        form3Layout.setHorizontalGroup(
            form3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form3Layout.createSequentialGroup()
                .addComponent(pane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        form3Layout.setVerticalGroup(
            form3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form3Layout.createSequentialGroup()
                .addGroup(form3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        form4.setBackground(new java.awt.Color(143, 137, 183));
        form4.setForeground(new java.awt.Color(255, 255, 255));
        form4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        form4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                form4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pane4Layout = new javax.swing.GroupLayout(pane4);
        pane4.setLayout(pane4Layout);
        pane4Layout.setHorizontalGroup(
            pane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane4Layout.setVerticalGroup(
            pane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Graphicloads-Food-Drink-Drink-4.24.png"))); // NOI18N
        jLabel6.setText("Sản phẩm");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout form4Layout = new javax.swing.GroupLayout(form4);
        form4.setLayout(form4Layout);
        form4Layout.setHorizontalGroup(
            form4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form4Layout.createSequentialGroup()
                .addComponent(pane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        form4Layout.setVerticalGroup(
            form4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form4Layout.createSequentialGroup()
                .addGroup(form4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        form5.setBackground(new java.awt.Color(143, 137, 183));
        form5.setForeground(new java.awt.Color(255, 255, 255));
        form5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        form5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                form5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pane5Layout = new javax.swing.GroupLayout(pane5);
        pane5.setLayout(pane5Layout);
        pane5Layout.setHorizontalGroup(
            pane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane5Layout.setVerticalGroup(
            pane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Graphicloads-100-Flat-Phonebook.24.png"))); // NOI18N
        jLabel7.setText("Loại hàng");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout form5Layout = new javax.swing.GroupLayout(form5);
        form5.setLayout(form5Layout);
        form5Layout.setHorizontalGroup(
            form5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form5Layout.createSequentialGroup()
                .addComponent(pane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(0, 34, Short.MAX_VALUE))
        );
        form5Layout.setVerticalGroup(
            form5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form5Layout.createSequentialGroup()
                .addGroup(form5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pane5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        form6.setBackground(new java.awt.Color(143, 137, 183));
        form6.setForeground(new java.awt.Color(255, 255, 255));
        form6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        form6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                form6MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pane6Layout = new javax.swing.GroupLayout(pane6);
        pane6.setLayout(pane6Layout);
        pane6Layout.setHorizontalGroup(
            pane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane6Layout.setVerticalGroup(
            pane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Graphicloads-100-Flat-Summary.24.png"))); // NOI18N
        jLabel8.setText("Thống kê");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        javax.swing.GroupLayout form6Layout = new javax.swing.GroupLayout(form6);
        form6.setLayout(form6Layout);
        form6Layout.setHorizontalGroup(
            form6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form6Layout.createSequentialGroup()
                .addComponent(pane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(0, 37, Short.MAX_VALUE))
        );
        form6Layout.setVerticalGroup(
            form6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form6Layout.createSequentialGroup()
                .addGroup(form6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pane6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDangXuat.setBackground(new java.awt.Color(232, 245, 200));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Papirus-Team-Papirus-Apps-System-log-out.24.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnDoiMatKhau.setBackground(new java.awt.Color(232, 245, 200));
        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Flat-Icons.com-Flat-Pencil.24.png"))); // NOI18N
        btnDoiMatKhau.setText("Thông tin");
        btnDoiMatKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Martz90-Circle-Addon2-Help.24.png"))); // NOI18N
        jLabel10.setText("Hướng dẫn");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        form7.setBackground(new java.awt.Color(143, 137, 183));
        form7.setForeground(new java.awt.Color(255, 255, 255));
        form7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        form7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                form7MousePressed(evt);
            }
        });

        javax.swing.GroupLayout pane7Layout = new javax.swing.GroupLayout(pane7);
        pane7.setLayout(pane7Layout);
        pane7Layout.setHorizontalGroup(
            pane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pane7Layout.setVerticalGroup(
            pane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Graphicloads-100-Flat-Note.24.png"))); // NOI18N
        jLabel11.setText("Hóa đơn");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        javax.swing.GroupLayout form7Layout = new javax.swing.GroupLayout(form7);
        form7.setLayout(form7Layout);
        form7Layout.setHorizontalGroup(
            form7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form7Layout.createSequentialGroup()
                .addComponent(pane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(0, 44, Short.MAX_VALUE))
        );
        form7Layout.setVerticalGroup(
            form7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(form7Layout.createSequentialGroup()
                .addGroup(form7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pane7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(form1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(form2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(form3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(form4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(form5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(form6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10)
                    .addComponent(btnDangXuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btnDoiMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(form7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(form1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(form2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(form3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(form4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(form5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(form7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(form6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoiMatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDangXuat)
                .addContainerGap())
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 160, 460));

        kGradientPanel1.setkEndColor(new java.awt.Color(234, 175, 200));
        kGradientPanel1.setkStartColor(new java.awt.Color(101, 78, 163));

        lblKiriko.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        lblKiriko.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Klukeart-Latex-Latex-Bottle.32.png"))); // NOI18N
        lblKiriko.setText("sssssss");
        lblKiriko.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKiriko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKirikoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblKiriko, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblKiriko)
                .addContainerGap())
        );

        getContentPane().add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        kGradientPanel2.setkEndColor(new java.awt.Color(143, 137, 183));
        kGradientPanel2.setkStartColor(new java.awt.Color(143, 137, 183));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/edusys/icon/Steve-Zondicons-Menu.24.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int x, y;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int xx = evt.getXOnScreen();
        int yy = evt.getYOnScreen();
        this.setLocation(xx - x, yy - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        boolean check = MsgBox.comfirm(this, "Bạn có muốn thoát?");

        if (check == true) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void form1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form1MousePressed
        // TODO add your handling code here:
        form1.setBackground(new Color(227, 80, 168));
        form2.setBackground(new Color(143, 137, 183));
        form3.setBackground(new Color(143, 137, 183));
        form4.setBackground(new Color(143, 137, 183));
        form5.setBackground(new Color(143, 137, 183));
        form6.setBackground(new Color(143, 137, 183));

        pane1.setBackground(paneclick);
        pane2.setBackground(panedefault);
        pane3.setBackground(panedefault);
        pane4.setBackground(panedefault);
        pane5.setBackground(panedefault);
        pane6.setBackground(panedefault);

        form7.setBackground(new Color(143, 137, 183));
        pane7.setBackground(panedefault);
    }//GEN-LAST:event_form1MousePressed

    private void form2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form2MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        }
        else if(!Auth.isManager()){
            MsgBox.alert(this, "Ban khong co quyen xem nhan vien");
        }
        else {
            form2.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane2.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane6.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_form2MousePressed

    private void form1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form1MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        TrangChu tc = new TrangChu();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_form1MouseClicked

    private void form2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form2MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        NhanVienForm ma = new NhanVienForm();
        jDesktopPane1.add(ma).setVisible(true);
    }//GEN-LAST:event_form2MouseClicked

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
        this.dangXuat();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void form3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form3MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        KhachHangForm tc = new KhachHangForm();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_form3MouseClicked

    private void form3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form3MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        } else {
            form3.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane3.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane2.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane6.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_form3MousePressed

    private void form4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form4MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        SanPhamForm tc = new SanPhamForm();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_form4MouseClicked

    private void form4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form4MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        } else {
            form4.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane4.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane2.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane6.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_form4MousePressed

    private void form5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form5MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        MatHangForm tc = new MatHangForm();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_form5MouseClicked

    private void form5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form5MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        } else {
            form5.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane5.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane2.setBackground(panedefault);
            pane6.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_form5MousePressed

    private void form6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form6MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        ThongKeForm tc = new ThongKeForm();
        jDesktopPane1.add(tc).setVisible(true);

    }//GEN-LAST:event_form6MouseClicked

    private void form6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form6MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        }
        else if(!Auth.isManager()){
            MsgBox.alert(this, "Ban khong co quyen xem doanh thu");
        } 
        else {
            form6.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));

            pane6.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane2.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_form6MousePressed
    NhanVienDAO dao = new NhanVienDAO();
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.openHuongDan();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        SanPhamForm tc = new SanPhamForm();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void form7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form7MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        HoaDonForm tc = new HoaDonForm();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_form7MouseClicked

    private void form7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form7MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        } else {
            form7.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane7.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane2.setBackground(panedefault);
            pane6.setBackground(panedefault);
        }
    }//GEN-LAST:event_form7MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        form1.setBackground(new Color(227, 80, 168));
        form2.setBackground(new Color(143, 137, 183));
        form3.setBackground(new Color(143, 137, 183));
        form4.setBackground(new Color(143, 137, 183));
        form5.setBackground(new Color(143, 137, 183));
        form6.setBackground(new Color(143, 137, 183));

        pane1.setBackground(paneclick);
        pane2.setBackground(panedefault);
        pane3.setBackground(panedefault);
        pane4.setBackground(panedefault);
        pane5.setBackground(panedefault);
        pane6.setBackground(panedefault);

        form7.setBackground(new Color(143, 137, 183));
        pane7.setBackground(panedefault);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        TrangChu tc = new TrangChu();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        }
        else if(!Auth.isManager()){
            MsgBox.alert(this, "Ban khong co quyen xem nhan vien");
        }
        else {
            form2.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane2.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane6.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        NhanVienForm ma = new NhanVienForm();
        jDesktopPane1.add(ma).setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        } else {
            form3.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane3.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane2.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane6.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        KhachHangForm tc = new KhachHangForm();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        } else {
            form4.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane4.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane2.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane6.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_jLabel6MousePressed

    private void lblKirikoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKirikoMouseClicked
        // TODO add your handling code here:
        if (Auth.isLogin()) {
            new GioiThieuJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại");
        }
    }//GEN-LAST:event_lblKirikoMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (menu.isVisible()) {
            menu.setVisible(false);

        } else {
            menu.setVisible(true);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        MatHangForm tc = new MatHangForm();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        } else {
            form5.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane5.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane2.setBackground(panedefault);
            pane6.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        HoaDonForm tc = new HoaDonForm();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        } else {
            form7.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));
            form6.setBackground(new Color(143, 137, 183));

            pane7.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane2.setBackground(panedefault);
            pane6.setBackground(panedefault);
        }
    }//GEN-LAST:event_jLabel11MousePressed

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        // TODO add your handling code here:
        NhanVien nv = dao.selectById(txtUS.getText());
        ThongTinForm a = new ThongTinForm(nv);

        a.setVisible(true);
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        ThongKeForm tc = new ThongKeForm();
        jDesktopPane1.add(tc).setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        // TODO add your handling code here:
        if (!Auth.isLogin()) {
            MsgBox.alert(this, "Vui long dang nhap lai");
        }
        else if(!Auth.isManager()){
            MsgBox.alert(this, "Ban khong co quyen xem doanh thu");
        }
        else {
            form6.setBackground(new Color(227, 80, 168));
            form1.setBackground(new Color(143, 137, 183));
            form3.setBackground(new Color(143, 137, 183));
            form4.setBackground(new Color(143, 137, 183));
            form5.setBackground(new Color(143, 137, 183));
            form2.setBackground(new Color(143, 137, 183));

            pane6.setBackground(paneclick);
            pane1.setBackground(panedefault);
            pane3.setBackground(panedefault);
            pane4.setBackground(panedefault);
            pane5.setBackground(panedefault);
            pane2.setBackground(panedefault);

            form7.setBackground(new Color(143, 137, 183));
            pane7.setBackground(panedefault);
        }
    }//GEN-LAST:event_jLabel8MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    private void init() {
        this.setLocationRelativeTo(null);
        lblKiriko.setText("KIRIKO");
        this.setIconImage(XImage.getAppIcon());
        new ChaoJDialog(this, true).setVisible(true);
        new DangNhapJDialog(this, true).setVisible(true);

        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh:mm:ss a");// 
                String text = formater.format(now);

                lblDongHo.setText(text);
            }
        }).start();

        new Timer(1500, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (null != lblKiriko.getText()) {
                    switch (lblKiriko.getText()) {
                        case "KIRIKO" ->
                            lblKiriko.setText("");
                        case "" ->
                            lblKiriko.setText("K");
                        case "K" ->
                            lblKiriko.setText("KI");
                        case "KI" ->
                            lblKiriko.setText("KIR");
                        case "KIR" ->
                            lblKiriko.setText("KIRI");
                        case "KIRI" ->
                            lblKiriko.setText("KIRIK");
                        case "KIRIK" ->
                            lblKiriko.setText("KIRIKO");
                        default -> {
                        }
                    }
                }
            }
        }).start();

        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");// dd/MM/yyyy
                String text = formater.format(now);

                lblNgayThang.setText(text);
            }
        }).start();
        txtUS.setText(Auth.user.getMaNV());
        txtRole.setText((Auth.user.isVaiTro() ? "Trưởng phòng" : "Nhân viên"));
    }

    private void dangXuat() {
        Auth.clear();
        txtUS.setText("null ");
        txtRole.setText("null");
        new DangNhapJDialog(this, true).setVisible(true);
        btnDangXuat.setText("Đăng nhập");
        if (Auth.isLogin()) {
            txtUS.setText(Auth.user.getMaNV());
            txtRole.setText((Auth.user.isVaiTro() ? "Trưởng phòng" : "Nhân viên"));
            btnDangXuat.setText("Đăng xuất");
        }
    }

    private void openDoiMatKhau() {
        //neu user da dang nhap thi moi hien cua so
        if (Auth.isLogin()) {
            new DoiMatKhauJDialog(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập lại");
        }
    }

    private void openHuongDan() {
        try {
            Desktop.getDesktop().browse(new File("help/index1.html").toURI());
        } catch (IOException e) {
            MsgBox.alert(this, "Không tìm thấy file hướng dẫn");
        }
    }
    
    private static void customizeButton(JButton button) {
        button.setPreferredSize(new Dimension(120, 50));
        button.setBackground(new Color(0, 150, 136));
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);

        button.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Xử lý khi click vào button
            }

            @Override
            public void mousePressed(MouseEvent e) {
                // Xử lý khi nhấn chuột
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                // Xử lý khi thả chuột
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                button.setBackground(new Color(244, 67, 54));
            }

            @Override
            public void mouseExited(MouseEvent e) {
                button.setBackground( new Color(0, 150, 136));
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JPanel form1;
    private javax.swing.JPanel form2;
    private javax.swing.JPanel form3;
    private javax.swing.JPanel form4;
    private javax.swing.JPanel form5;
    private javax.swing.JPanel form6;
    private javax.swing.JPanel form7;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblKiriko;
    private javax.swing.JLabel lblNgayThang;
    private keeptoo.KGradientPanel menu;
    private javax.swing.JPanel pane1;
    private javax.swing.JPanel pane2;
    private javax.swing.JPanel pane3;
    private javax.swing.JPanel pane4;
    private javax.swing.JPanel pane5;
    private javax.swing.JPanel pane6;
    private javax.swing.JPanel pane7;
    private javax.swing.JPanel trangThai;
    private javax.swing.JLabel txtRole;
    private javax.swing.JLabel txtUS;
    // End of variables declaration//GEN-END:variables
}
